language: cpp
matrix:
  include:
    - os: windows
      env:
      - LABEL="windows-msvc"
      - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
      script:
      - export PATH=$MSBUILD_PATH:$PATH
      - MSBuild.exe Project/AStarSearch/A_Star_Search.sln /p:Configuration="Release"

before_install:
    - eval "${MATRIX_EVAL}"
